//
//  Colors.swift
//  Generated by Token Converter
//

import SwiftUI

extension Color {
    static let Background = Color(red: 0.957, green: 0.239, blue: 0.345)
    static let BackgroundSubdued = Color(red: 0.722, green: 0.004, blue: 0.110)
    static let BackgroundElevated = Color(red: 0.890, green: 0.918, blue: 0.973)
    static let BackgroundInverted = Color(red: 0.000, green: 0.000, blue: 0.031)
    static let BackgroundInteractive = Color(red: 0.588, green: 0.306, blue: 0.937)
    static let BackgroundDisabled = Color(red: 0.655, green: 0.682, blue: 0.737)
    static let BackgroundSuccess = Color(red: 0.376, green: 0.063, blue: 0.306)
    static let BackgroundWarning = Color(red: 1.000, green: 1.000, blue: 1.000)
    static let BackgroundError = Color(red: 0.933, green: 0.898, blue: 0.957)
    static let BackgroundInfo = Color(red: 0.973, green: 0.212, blue: 0.824)
    static let Text = Color(red: 0.000, green: 0.000, blue: 0.031)
    static let TextMuted = Color(red: 0.302, green: 0.329, blue: 0.384)
    static let TextSubtle = Color(red: 0.302, green: 0.329, blue: 0.384)
    static let TextInverted = Color(red: 0.969, green: 0.996, blue: 1.000)
    static let TextOnPrimary = Color(red: 1.000, green: 0.855, blue: 1.000)
    static let TextOnSecondary = Color(red: 1.000, green: 0.671, blue: 0.776)
    static let TextOnSuccess = Color(red: 0.925, green: 0.612, blue: 0.855)
    static let TextOnWarning = Color(red: 1.000, green: 1.000, blue: 0.902)
    static let TextOnError = Color(red: 1.000, green: 1.000, blue: 1.000)
    static let TextOnInfo = Color(red: 1.000, green: 0.761, blue: 1.000)
    static let Border = Color(red: 0.655, green: 0.682, blue: 0.737)
    static let BorderSubtle = Color(red: 0.773, green: 0.800, blue: 0.855)
    static let BorderStrong = Color(red: 0.184, green: 0.212, blue: 0.267)
    static let BorderDisabled = Color(red: 0.537, green: 0.565, blue: 0.620)
    static let BorderSuccess = Color(red: 0.259, green: 0.000, blue: 0.188)
    static let BorderWarning = Color(red: 0.859, green: 0.753, blue: 0.235)
    static let BorderError = Color(red: 0.816, green: 0.780, blue: 0.839)
    static let BorderInfo = Color(red: 0.855, green: 0.094, blue: 0.706)
    static let Surface = Color(red: 1.000, green: 1.000, blue: 1.000)
    static let SurfaceMuted = Color(red: 1.000, green: 1.000, blue: 1.000)
    static let SurfaceElevated = Color(red: 1.000, green: 1.000, blue: 1.000)
    static let SurfaceOverlay = Color(red: 0.627, green: 0.627, blue: 0.627)
    static let SurfaceDisabled = Color(red: 1.000, green: 1.000, blue: 1.000)
    static let SurfaceContrast = Color(red: 0.510, green: 0.510, blue: 0.510)
}