//
//  Theme.swift
//  Generated by Token Converter
//

import SwiftUI

struct Theme {
    static let Background = Color.Background
    static let BackgroundSubdued = Color.BackgroundSubdued
    static let BackgroundElevated = Color.BackgroundElevated
    static let BackgroundInverted = Color.BackgroundInverted
    static let BackgroundInteractive = Color.BackgroundInteractive
    static let BackgroundDisabled = Color.BackgroundDisabled
    static let BackgroundSuccess = Color.BackgroundSuccess
    static let BackgroundWarning = Color.BackgroundWarning
    static let BackgroundError = Color.BackgroundError
    static let BackgroundInfo = Color.BackgroundInfo
    static let Text = Color.Text
    static let TextMuted = Color.TextMuted
    static let TextSubtle = Color.TextSubtle
    static let TextInverted = Color.TextInverted
    static let TextOnPrimary = Color.TextOnPrimary
    static let TextOnSecondary = Color.TextOnSecondary
    static let TextOnSuccess = Color.TextOnSuccess
    static let TextOnWarning = Color.TextOnWarning
    static let TextOnError = Color.TextOnError
    static let TextOnInfo = Color.TextOnInfo
    static let Border = Color.Border
    static let BorderSubtle = Color.BorderSubtle
    static let BorderStrong = Color.BorderStrong
    static let BorderDisabled = Color.BorderDisabled
    static let BorderSuccess = Color.BorderSuccess
    static let BorderWarning = Color.BorderWarning
    static let BorderError = Color.BorderError
    static let BorderInfo = Color.BorderInfo
    static let Surface = Color.Surface
    static let SurfaceMuted = Color.SurfaceMuted
    static let SurfaceElevated = Color.SurfaceElevated
    static let SurfaceOverlay = Color.SurfaceOverlay
    static let SurfaceDisabled = Color.SurfaceDisabled
    static let SurfaceContrast = Color.SurfaceContrast
}